files:
  - source: /core/src/main/resources/*.properties
    translation: /**/%original_file_name%_%two_letters_code%.%file_extension%
  - source: /front/public/messages/**/*.json
    translation: '%original_path%/%file_name%_translated.%file_extension%'
